import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { detectAgents } from "../adapters/index.js";
import {
  captureConfigPath,
  findVitestConfig,
  type ProjectContext,
} from "../cli/context.js";
import { rebuildIndex } from "./rebuild.js";

export interface InitResult {
  agents: string[];
  captureConfig: string;
  userConfig?: string;
  indexedTests?: number;
}

/** Absolute path to the shipped Vitest setup file (dev: .ts, built: .js). */
function resolveSetupPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  for (const ext of ["js", "ts"]) {
    const candidate = path.join(here, "..", "coverage", `setup.${ext}`);
    if (existsSync(candidate)) return candidate;
  }
  return path.join(here, "..", "coverage", "setup.js");
}

/**
 * Build a Vitest config that extends the project's own config with the
 * sherlockbones setup file and istanbul coverage. Kept separate from the user's
 * config so we never mutate their file.
 */
export function generateCaptureConfig(
  userConfig: string | undefined,
  setupPath: string,
): string {
  const baseImport = userConfig
    ? `import base from ${JSON.stringify(userConfig)};`
    : "const base = {};";

  // The user config may be the callback form `defineConfig((env) => ({...}))`,
  // which exports a function. mergeConfig rejects functions, so resolve it first.
  return `// Generated by \`bones init\`. Do not edit.
import { defineConfig, mergeConfig } from "vitest/config";
${baseImport}

const resolvedBase =
  typeof base === "function" ? await base({ mode: "test", command: "serve" }) : base;

export default mergeConfig(
  resolvedBase,
  defineConfig({
    test: {
      setupFiles: [${JSON.stringify(setupPath)}],
      coverage: { provider: "istanbul", enabled: true, reporter: [] },
    },
  }),
);
`;
}

/**
 * Set up sherlockbones in a project: install hooks for detected agents and write
 * the capture config that makes coverage rebuilds work. Optionally builds the
 * initial index.
 */
export function init(ctx: ProjectContext, opts: { rebuild?: boolean } = {}): InitResult {
  const agents = detectAgents(ctx.root).map((adapter) => {
    adapter.install(ctx.root);
    return adapter.name;
  });

  const userConfig = findVitestConfig(ctx.root);
  const captureConfig = captureConfigPath(ctx.root);
  mkdirSync(path.dirname(captureConfig), { recursive: true });
  writeFileSync(captureConfig, generateCaptureConfig(userConfig, resolveSetupPath()));

  const result: InitResult = { agents, captureConfig, userConfig };

  if (opts.rebuild) {
    result.indexedTests = rebuildIndex({ ...ctx, configPath: captureConfig }).tests;
  }
  return result;
}
